// <auto-generated />
using System;
using ArandanoIRT.Web._0_Domain.Entities;
using ArandanoIRT.Web._2_Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArandanoIRT.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.AnalysisResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float?>("AmbientTemperature")
                        .HasColumnType("real")
                        .HasColumnName("ambient_temperature");

                    b.Property<float?>("BaselineLL")
                        .HasColumnType("real")
                        .HasColumnName("baseline_ll");

                    b.Property<float?>("BaselineUL")
                        .HasColumnType("real")
                        .HasColumnName("baseline_ul");

                    b.Property<float?>("CanopyTemperature")
                        .HasColumnType("real")
                        .HasColumnName("canopy_temperature");

                    b.Property<float?>("CwsiValue")
                        .HasColumnType("real")
                        .HasColumnName("cwsi_value");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_id");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<float?>("Vpd")
                        .HasColumnType("real")
                        .HasColumnName("vpd");

                    b.HasKey("Id")
                        .HasName("analysis_results_pkey");

                    b.HasIndex("PlantId", "RecordedAt")
                        .IsUnique();

                    b.HasIndex(new[] { "PlantId", "RecordedAt" }, "idx_analysis_results_plant_id_recorded_at")
                        .IsDescending(false, true);

                    b.ToTable("analysis_results", null, t =>
                        {
                            t.HasComment("Stores calculated results from the analysis module for optimal reporting and full auditability.");
                        });
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.Crop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<CropSettings>("CropSettings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("crop_settings");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("crops_pkey");

                    b.ToTable("crops", null, t =>
                        {
                            t.HasComment("Stores information about crops. Acts as the main grouping entity (tenant).");
                        });
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CropId")
                        .HasColumnType("integer")
                        .HasColumnName("crop_id");

                    b.Property<short>("DataCollectionIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)15)
                        .HasColumnName("data_collection_interval_minutes");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("MacAddress")
                        .HasColumnType("text")
                        .HasColumnName("mac_address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PlantId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_id");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("devices_pkey");

                    b.HasIndex("CropId");

                    b.HasIndex(new[] { "MacAddress" }, "devices_mac_address_key")
                        .IsUnique();

                    b.HasIndex(new[] { "MacAddress" }, "idx_devices_mac_address");

                    b.HasIndex(new[] { "PlantId" }, "idx_devices_plant_id");

                    b.ToTable("devices", null, t =>
                        {
                            t.HasComment("Stores physical monitoring hardware devices.");
                        });
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.DeviceActivation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<string>("ActivationCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activation_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("device_activations_pkey");

                    b.HasIndex("DeviceId");

                    b.HasIndex(new[] { "ActivationCode" }, "device_activations_activation_code_key")
                        .IsUnique();

                    b.ToTable("device_activations", null, t =>
                        {
                            t.HasComment("Stores single-use codes to activate new devices.");
                        });
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.DeviceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTime>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_token_expires_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("device_tokens_pkey");

                    b.HasIndex("DeviceId");

                    b.HasIndex(new[] { "AccessToken" }, "device_tokens_access_token_key")
                        .IsUnique();

                    b.HasIndex(new[] { "RefreshToken" }, "device_tokens_refresh_token_key")
                        .IsUnique();

                    b.ToTable("device_tokens", null, t =>
                        {
                            t.HasComment("Stores authentication tokens (JWTs) for devices.");
                        });
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.EnvironmentalReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float?>("CityHumidity")
                        .HasColumnType("real")
                        .HasColumnName("city_humidity");

                    b.Property<float?>("CityTemperature")
                        .HasColumnType("real")
                        .HasColumnName("city_temperature");

                    b.Property<string>("CityWeatherCondition")
                        .HasColumnType("text")
                        .HasColumnName("city_weather_condition");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<string>("ExtraData")
                        .HasColumnType("jsonb")
                        .HasColumnName("extra_data");

                    b.Property<float>("Humidity")
                        .HasColumnType("real")
                        .HasColumnName("humidity");

                    b.Property<int?>("PlantId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_id");

                    b.Property<DateTime?>("RecordedAtDevice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_device")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("RecordedAtServer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_server")
                        .HasDefaultValueSql("now()");

                    b.Property<float>("Temperature")
                        .HasColumnType("real")
                        .HasColumnName("temperature");

                    b.HasKey("Id")
                        .HasName("environmental_readings_pkey");

                    b.HasIndex(new[] { "DeviceId", "RecordedAtServer" }, "idx_readings_device_id_recorded_at_server")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "PlantId", "RecordedAtServer" }, "idx_readings_plant_id_recorded_at_server")
                        .IsDescending(false, true);

                    b.ToTable("environmental_readings", null, t =>
                        {
                            t.HasComment("Stores environmental data collected by device sensors.");
                        });
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.InvitationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.HasKey("Id")
                        .HasName("invitation_codes_pkey");

                    b.HasIndex(new[] { "CreatedByUserId" }, "idx_invitation_codes_created_by_user_id");

                    b.HasIndex(new[] { "Code" }, "invitation_codes_code_key")
                        .IsUnique();

                    b.ToTable("invitation_codes", null, t =>
                        {
                            t.HasComment("Stores single-use invitation codes for user registration.");
                        });
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_id");

                    b.Property<short?>("SubjectiveRating")
                        .HasColumnType("smallint")
                        .HasColumnName("subjective_rating");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("observations_pkey");

                    b.HasIndex(new[] { "PlantId" }, "idx_observations_plant_id");

                    b.HasIndex(new[] { "UserId" }, "idx_observations_user_id");

                    b.ToTable("observations", null, t =>
                        {
                            t.HasComment("Stores manual observations made by an agronomist or expert user.");
                        });
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CropId")
                        .HasColumnType("integer")
                        .HasColumnName("crop_id");

                    b.Property<int>("ExperimentalGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("experimental_group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4)
                        .HasColumnName("status");

                    b.Property<string>("ThermalMaskData")
                        .HasColumnType("jsonb")
                        .HasColumnName("thermal_mask_data");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("plants_pkey");

                    b.HasIndex(new[] { "CropId" }, "idx_plants_crop_id");

                    b.HasIndex(new[] { "Status" }, "idx_plants_status");

                    b.ToTable("plants", null, t =>
                        {
                            t.HasComment("Stores data for each monitored plant.");
                        });
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.PlantStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Observation")
                        .HasColumnType("text")
                        .HasColumnName("observation");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("plant_status_histories_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ChangedAt" }, "idx_plant_status_histories_changed_at")
                        .IsDescending();

                    b.HasIndex(new[] { "PlantId" }, "idx_plant_status_histories_plant_id");

                    b.ToTable("plant_status_histories", null, t =>
                        {
                            t.HasComment("Stores the history of status changes for each plant.");
                        });
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.ThermalCapture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<int?>("PlantId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_id");

                    b.Property<DateTime?>("RecordedAtDevice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_device")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("RecordedAtServer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_server")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RgbImagePath")
                        .HasColumnType("text")
                        .HasColumnName("rgb_image_path");

                    b.Property<string>("ThermalDataStats")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("thermal_data_stats");

                    b.HasKey("Id")
                        .HasName("thermal_captures_pkey");

                    b.HasIndex(new[] { "DeviceId", "RecordedAtServer" }, "idx_captures_device_id_recorded_at_server")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "PlantId", "RecordedAtServer" }, "idx_captures_plant_id_recorded_at_server")
                        .IsDescending(false, true);

                    b.ToTable("thermal_captures", null, t =>
                        {
                            t.HasComment("Stores thermographic captures. Statistics are stored in JSONB, the image path in Object Storage.");
                        });
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<AccountSettings>("AccountSettings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("account_settings");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("first_name");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.AnalysisResult", b =>
                {
                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.Plant", "Plant")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("analysis_results_plant_id_fkey");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.Device", b =>
                {
                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.Crop", "Crop")
                        .WithMany("Devices")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("devices_crop_id_fkey");

                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.Plant", "Plant")
                        .WithMany("Devices")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("devices_plant_id_fkey");

                    b.Navigation("Crop");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.DeviceActivation", b =>
                {
                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.Device", "Device")
                        .WithMany("DeviceActivations")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("device_activations_device_id_fkey");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.DeviceToken", b =>
                {
                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.Device", "Device")
                        .WithMany("DeviceTokens")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("device_tokens_device_id_fkey");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.EnvironmentalReading", b =>
                {
                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.Device", "Device")
                        .WithMany("EnvironmentalReadings")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("environmental_readings_device_id_fkey");

                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.Plant", "Plant")
                        .WithMany("EnvironmentalReadings")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("environmental_readings_plant_id_fkey");

                    b.Navigation("Device");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.InvitationCode", b =>
                {
                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.User", "CreatedByUser")
                        .WithMany("InvitationCodes")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("invitation_codes_created_by_user_id_fkey");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.Observation", b =>
                {
                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.Plant", "Plant")
                        .WithMany("Observations")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("observations_plant_id_fkey");

                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.User", "User")
                        .WithMany("Observations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("observations_user_id_fkey");

                    b.Navigation("Plant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.Plant", b =>
                {
                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.Crop", "Crop")
                        .WithMany("Plants")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("plants_crop_id_fkey");

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.PlantStatusHistory", b =>
                {
                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.Plant", "Plant")
                        .WithMany("PlantStatusHistories")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("plant_status_histories_plant_id_fkey");

                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.User", "User")
                        .WithMany("PlantStatusHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("plant_status_histories_user_id_fkey");

                    b.Navigation("Plant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.ThermalCapture", b =>
                {
                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.Device", "Device")
                        .WithMany("ThermalCaptures")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("thermal_captures_device_id_fkey");

                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.Plant", "Plant")
                        .WithMany("ThermalCaptures")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("thermal_captures_plant_id_fkey");

                    b.Navigation("Device");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ArandanoIRT.Web._0_Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.Crop", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Plants");
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.Device", b =>
                {
                    b.Navigation("DeviceActivations");

                    b.Navigation("DeviceTokens");

                    b.Navigation("EnvironmentalReadings");

                    b.Navigation("ThermalCaptures");
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.Plant", b =>
                {
                    b.Navigation("AnalysisResults");

                    b.Navigation("Devices");

                    b.Navigation("EnvironmentalReadings");

                    b.Navigation("Observations");

                    b.Navigation("PlantStatusHistories");

                    b.Navigation("ThermalCaptures");
                });

            modelBuilder.Entity("ArandanoIRT.Web._0_Domain.Entities.User", b =>
                {
                    b.Navigation("InvitationCodes");

                    b.Navigation("Observations");

                    b.Navigation("PlantStatusHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
