name: CI - Build and Analyze

# Disparador: Se ejecuta en cada PUSH a cualquier rama EXCEPTO main.
# También incluye optimizaciones para no ejecutarse si solo cambian archivos no relevantes (como .md).
on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '.github/workflows/ci.yml' # Para que se ejecute si cambiamos el propio workflow
  workflow_dispatch: # Permite la ejecución manual desde la pestaña Actions
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Job 1: Construir el proyecto para asegurar que compila
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true # Optimización: Activa el caché para los paquetes de NuGet

      - name: Build
        run: dotnet build ArandanoIRT.sln --configuration Release

  # Job 2: Verificar el formato del código (Linting)
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run Linter
        run: dotnet format ArandanoIRT.sln --verify-no-changes --verbosity diagnostic

  # Job 3: Análisis estático de seguridad con CodeQL
  codeql:
    name: Analyze with CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write # Permiso necesario para que CodeQL suba los resultados

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3